name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Git Config
        run: |
          git config user.name "nilzona"
          git config user.email "nilssonanders79@gmail.com"
      - uses: pnpm/action-setup@v3
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - name: Install Dependencies
        run: pnpm i
      - name: Build Packages
        run: pnpm build
      - name: Create Release Pull Request or Publish to Qlik GitHub Packages npm registry
        id: changesets
        uses: changesets/action@v1
        with:
          setupGitUser: false
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
