name: Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Git Config
        run: |
          git config user.name "svc-pipeline"
          git config user.email "svc_pipeline@qlik.com"

      - name: Use pnpm 7
        uses: pnpm/action-setup@v2
        with:
          version: 7

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm

      - name: Setup access to qlik npm registry
        uses: qlik-trial/qmfe-workflows/actions/npm-github-access@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Dependencies
        run: pnpm i

      - name: Create Release Pull Request or Publish to Qlik GitHub Packages npm registry
        id: changesets
        uses: changesets/action@v1
        with:
          setupGitUser: false
          commit: "chore(release): version packages"
          title: "chore(release): version packages"
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
