name: validate

on:
  push:
    branches:
      - "main"
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches:
      - "main"

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
          cache: yarn
      - run: yarn
      - run: yarn build
      - run: yarn format:check
      - run: yarn lint
      - run: yarn test
